# air.toml

exclude_dir = ["vendor", "node_modules", "tmp"]
include_ext = ["go"]
exclude_file = ["air.toml"]
colors = true

[build]
cmd = "go run ./cmd/main.go"
bin = "./tmp/main"
full_bin = "./tmp/main"
full_bin = true
restart = true
clear = true
