services:
  app:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "443:443"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - mynetwork
    volumes:
      - ./certmagic-storage:/app/certmagic-storage  # Монтируем папку для хранения сертификатов

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data/
    ports:
      - 5432:5432
    volumes:
      - newDB:/var/lib/postgresql/data/
    networks:
      - mynetwork

  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redis:/data  # Для постоянства данных Redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - mynetwork

volumes:
  newDB:
  redis:

networks:
  mynetwork:
    external: true